#!/usr/bin/python

import time, os, glob, argparse
from subprocess import call

#program is written from top to bottom. to go with the flow, you should start at bottom.
#basic outline: run() reads options from command line and checks for PNG existance --> Creator reads options --> instructs Gif object how to be created.

class Gif():
    def __init__(self, res):
        """sets up gif object with name and path."""
        self.name = "gifCreation-" + time.strftime("%Y-%d-%m-%H-%M")
        self.path = "~/Pictures/Gifs/" + self.name + ".gif"
        self.source = sorted(glob.glob('*.png'))
        self.res = res
        self.command = 'convert -delay 5 -loop 0 -resize ' + res + ' -coalesce -layers OptimizePlus ' + ' '.join(self.source) + ' ~/Pictures/Gifs/' + self.name + '.gif'
    def normal(self):
        """The actual creation of a normal GIF. Takes a resolution as argument. Uses convert from ImageMagick"""
        call(self.command, shell = True)
    def eternal(self):
        """Creates a gif that goes back and forth in a loop eternally"""
        second_list = list(reversed(self.source[1:-1]))
        self.source = list(self.source + second_list)
        call(self.command, shell = True)
    def backwards(self):
        """Creates a gif that goes backwards"""
        self.source = list(reversed(self.source))
        call(self.command, shell=True)
    def checkSize(self):
        """Checks size of GIF file and returns it"""
        #formatted floating point so it shows only two first decimals.
        size = float("{0:.2f}".format(os.path.getsize(os.path.expanduser(self.path)) / (1024*1024.0)))
        return(size)

def Creator(res, style, limit):
    """A function that creates gif objects with propierties: resolution, style, size limit"""
    gif = Gif(res)
    if style == 'eternal':
        gif.eternal()
    elif style == 'backwards':
        gif.backwards()
    else:
        gif.normal()
    filesize = gif.checkSize()
    if filesize > float(limit):
        print("Success, but size is " + str(filesize) + "MB. I'll try again")
        os.remove(os.path.expanduser(gif.path))
        if filesize > limit + 10:
            Creator(str(int((int(res)*0.60))), style, limit)
        elif filesize > limit + 5:
            Creator(str(int((int(res)*0.75))), style, limit)
        else:
            Creator(str(int((int(res)*0.90))), style, limit)
    else:
        print("Your gif was generated succesfully. \n PATH: " + gif.path + "\n RESOLUTION: " + res + "px \n SIZE: " + str(gif.checkSize()) + " MB")

def run():
    try:
        glob.glob('*.png')
    except:
        print("Looks like there are not PNG files to work with here.")
    parser = argparse.ArgumentParser(description='Creates animated gif files using as a source all PNG found in the current directory.')
    parser.add_argument('-r', '--res', default=500, help='sets the resolution for the widest border of the gif. If blank is set to 500')
    parser.add_argument('-s', '--style', default='normal', help='you can create a NORMAL gif, an ETERNAL gif wich loops backs and forth or a BACKWARDS gif starting at the end of the file list. If blank or unrecognised is set to NORMAL')
    parser.add_argument('-l', '--limit', default=3, help='limits the filesize of your gif to INTEGER megabytes. If the gif is bigger, it will start again with a smaller resolution. If blank is set to 3 MB')
    arguments = parser.parse_args()
    res = str(arguments.res)
    style = arguments.style
    limit = arguments.limit
    print("Creating a gif for you with the following settings: \n STYLE: " + style + "\n RESOLUTION: " + res + "\n SIZE LIMIT: "+ str(limit))
    Creator(res, style, limit)

run()